### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/NugetVersionChecker#3]
### I have done the items below . . .

- [X] I have created a title but left the 🚧 emoji behind.

### Description

Rename this repo to **NugetExistsChecker**

### Acceptance Criteria

**This issue is finished when:**
- [ ] Repo renamed

### ToDo Items

- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
